# build stage
FROM golang:alpine AS build-env
COPY . /src
RUN cd /src && go build -o mendErr

# final stage
#FROM vandhanak/bcftools:1.3.1 (works but old)
FROM mercury/bcftools-1.6

#Must be set to use plugins (that's changed location)
ENV BCFTOOLS_PLUGINS=/usr/local/libexec/bcftools

COPY --from=build-env /src/mendErr /app/mendErr
WORKDIR /app

